<div class="footer-subscribe">
	<div class="title"><?php echo $this->__('Sign up & Get 10% off.') ?></div>
	<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="footer-newsletter-validate-detail">
		<p>Registra tu correo para recibir noticias y ofertas especiales</p>
		<button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Enviar')) ?>" class="button">
			<span><span><?php echo Mage::helper('core')->quoteEscape($this->__('Enviar')) ?></span></span></button>
		<div class="input-box">
		<input type="text" name="email" id="footer-newsletter"
		       title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>"
		       class="input-text required-entry validate-email"
		       value="<?php echo Mage::helper('core')->quoteEscape($this->__('Escribe tu correo aquí')) ?>"
		       onfocus="if ( this.value == '<?php echo Mage::helper('core')->quoteEscape($this->__('Escribe tu correo aquí')) ?>' ) { this.value = '' }"
		       onblur="if ( this.value == '' ) { this.value = '<?php echo Mage::helper('core')->quoteEscape($this->__('Escribe tu correo aquí')) ?>' }"
			/>
		</div>
		<div class="clear"></div>
	</form>
	<script type="text/javascript">
		//<![CDATA[
		var newsletterSubscriberFormDetail = new VarienForm('footer-newsletter-validate-detail');
		//]]>
	</script>
</div>